name: Release

on:
  push:
    branches: [master]

jobs:
  Release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coverage

      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Build library
        run: npm run build

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          user_name: 'Francisco Vena'
          user_email: 'fvena32@gmail.com'
